title:              jeongmin's Blog
email:              tory2174@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Leejeongmin
ljm1102url:                "https://ljm1102.github.io"

# Social Profiles
twitter_username:   Leejeongmin
github_username:    Leejeongmin
facebook_username:  Leejeongmin
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
